[package]
name = "autohmjvis"
authors = ["13th Eye <jjhh@13theye.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
autohmjcommon = { workspace = true }
deeplx = { version = "1", default-features = false }
futures-util = "0.3"
hangeul = "0.4.0"
rustkorean = "1.1"
nannou = { workspace = true }
nannou_osc = { workspace = true }
nnpipe = { workspace = true }
reqwest = "0.12"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = "0.26"
toml = { workspace = true }

[lib]
name = "autohmjvis"
path = "src/lib.rs"

[[bin]]
name = "autohmjvis"
path = "src/main.rs"