[package]
name = "autohmjvis"
authors = ["13th Eye <jjhh@13theye.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
autohmjcommon = { path = "../autohmjcommon" }
deeplx = { version = "1", default-features = false }
hangeul = "0.4.0"
rustkorean = "1.1.2"
nannou = "0.19"
nannou_egui = "0.19"
nnpipe = { git = "https://github.com/13theye/nnpipe", branch = "main" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = {version = "1"}
tungstenite = "0.26"
toml = "0.8"

[lib]
name = "autohmjvis"
path = "src/lib.rs"

[[bin]]
name = "autohmjvis"
path = "src/main.rs"