# config.toml
[server]
port = 50001

[ai_provider]
# When local is true, then uses the OpenAI API for a LMStudio-hosted model.
# When false, uses Gemma in the cloud.
local = false

[osc_send]
# OSC receiver's IP address (String)
target_addr = "127.0.0.1"
# OSC receiver's port.
target_port = 45602

[tempo]
bpm = 236

[rendering_main]
texture_width = 3840
texture_height = 2160
# Please don't change these
texture_samples = 1
arc_resolution = 25

[audience_window]
# The size of the monitoring window.
# Currently scaling to 1/2 of texture resolution
width = 1920
height = 1080

[performer_window]
# The size of the performer window.
width = 1440
height = 810

[grid]
# all in integers
font_size_text = 100
font_size_translation = 46
font_size_statusbar = 30

grid_rows = 11
grid_cols = 8

# margin between screen edges and grid
top_margin = 120
bottom_margin = 120
left_margin = 96
right_margin = 96
# spacing between grids
grid_spacing = 90
# cell size
cell_width = 140
cell_height = 170
# grid lines
grid_line_stroke = 4
margin_line_stroke = 2

[paths]
#paths are relative to executable directory
# directory to save recordings:
output_directory = "frames"
# directory for key.toml: secret keys
auth = "auth"
# directory for ai.toml: AI config:
ai = "ai"
# path to intro image:
intro_image = "intro.png"


[translation]
# Enable or disable automatic translation of conversation messages
enabled = true
# Enable or disable a second automatic translation of conversation messages
enable_second_language = true
# Target language
target_language = "en"
# Second target language
second_target_language = "es"
# Translation backend: "deeplx" or "local_ai"
provider = "local_ai"
